[project]
name = "geoglows_ecflow"
version = "0.1.0"
description = "ECFLOW RAPID workflow for GEOGloWS"
authors = [
    {name = "Michael Souffront", email = "msouffront@aquaveo.com"},
    {name = "Riley Hales", email = "rchales@byu.edu"},
]
dependencies = [
    "pyyaml>=6.0.1",
    "numpy>=1.25.2",
    "netcdf4>=1.6.4",
    "pandas>=2.1.0",
    "fastparquet>=2023.8.0",
    "basininflow>=0.4.0",
    "RAPIDpy>=2.6.0",  # Install manually
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "BSD-3-Clause"}

[project.optional-dependencies]
test = [
    "pytest>=7.4.2",
    "pytest-mock>=3.11.1",
    "pytest-cov>=4.1.0",
    "basininflow>=0.1.0",
    "netcdf4>=1.6.4",
]

[tool.coverage.report]
show_missing = true

[tool.setuptools]
packages = ["geoglows_ecflow"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
